CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY DEFAULT generate_random_id(6),
    name VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone_code VARCHAR(20) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    password TEXT NOT NULL,
    terms BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
