CREATE TABLE IF NOT EXISTS email_codes (
  email VARCHAR(255) NOT NULL,
  code SMALLINT NOT NULL,
  used BOOLEAN DEFAULT FALSE,
  expiry TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
